galaxy_info:
  author: wangwenpei
  description: Install Portable PyPy for Linux.
  company: 1024.engineer
  license: GPLv3
  min_ansible_version: 2.0
  platforms:
  - name: EL
    versions:
    - 6
    - 7
  - name: Debian
    versions:
    - all
  - name: Ubuntu
    versions:
    - all
  galaxy_tags:
    - system
    - python

dependencies: []

